package com.cma.intervideo.pojo;

// Generated 2009-10-2 19:10:14 by Hibernate Tools 3.2.4.GA

/**
 * ConfUnit generated by hbm2java
 */
public class ConfUnit implements java.io.Serializable {

	private Integer confUnitId;
	private int conferenceId;
	private int unitId;

	public ConfUnit() {
	}

	public ConfUnit(int conferenceId, int unitId) {
		this.conferenceId = conferenceId;
		this.unitId = unitId;
	}

	public Integer getConfUnitId() {
		return this.confUnitId;
	}

	public void setConfUnitId(Integer confUnitId) {
		this.confUnitId = confUnitId;
	}

	public int getConferenceId() {
		return this.conferenceId;
	}

	public void setConferenceId(int conferenceId) {
		this.conferenceId = conferenceId;
	}

	public int getUnitId() {
		return this.unitId;
	}

	public void setUnitId(int unitId) {
		this.unitId = unitId;
	}

}
