package com.cma.intervideo.pojo;

// Generated 2009-8-20 4:02:54 by Hibernate Tools 3.2.4.GA

/**
 * Privilege generated by hbm2java
 */
public class Privilege implements java.io.Serializable {

	private Integer privilegeId;
	private String name;
	private String url;
	private String description;
	private String code;

	public Privilege() {
	}

	public Privilege(String name) {
		this.name = name;
	}

	public Privilege(String name, String url, String description, String code) {
		this.name = name;
		this.url = url;
		this.description = description;
		this.code = code;
	}

	public Integer getPrivilegeId() {
		return this.privilegeId;
	}

	public void setPrivilegeId(Integer privilegeId) {
		this.privilegeId = privilegeId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}
	
	

}
