package com.cma.intervideo.pojo;

// Generated Jan 17, 2010 1:18:25 PM by Hibernate Tools 3.2.4.GA

/**
 * RecurrenceUnit generated by hbm2java
 */
public class RecurrenceUnit implements java.io.Serializable {

	private Integer recurrenceUnitId;
	private int recurrenceId;
	private int unitId;

	public RecurrenceUnit() {
	}

	public RecurrenceUnit(int recurrenceId, int unitId) {
		this.recurrenceId = recurrenceId;
		this.unitId = unitId;
	}

	public Integer getRecurrenceUnitId() {
		return this.recurrenceUnitId;
	}

	public void setRecurrenceUnitId(Integer recurrenceUnitId) {
		this.recurrenceUnitId = recurrenceUnitId;
	}

	public int getRecurrenceId() {
		return this.recurrenceId;
	}

	public void setRecurrenceId(int recurrenceId) {
		this.recurrenceId = recurrenceId;
	}

	public int getUnitId() {
		return this.unitId;
	}

	public void setUnitId(int unitId) {
		this.unitId = unitId;
	}

}
