package com.cma.intervideo.pojo;

// Generated 2009-8-20 4:02:54 by Hibernate Tools 3.2.4.GA

/**
 * RolePrivilegeId generated by hbm2java
 */
public class RolePrivilegeId implements java.io.Serializable {

	private int roleId;
	private int privilegeId;

	public RolePrivilegeId() {
	}

	public RolePrivilegeId(int roleId, int privilegeId) {
		this.roleId = roleId;
		this.privilegeId = privilegeId;
	}

	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	public int getPrivilegeId() {
		return this.privilegeId;
	}

	public void setPrivilegeId(int privilegeId) {
		this.privilegeId = privilegeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RolePrivilegeId))
			return false;
		RolePrivilegeId castOther = (RolePrivilegeId) other;

		return (this.getRoleId() == castOther.getRoleId())
				&& (this.getPrivilegeId() == castOther.getPrivilegeId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRoleId();
		result = 37 * result + this.getPrivilegeId();
		return result;
	}

}
