package com.cma.intervideo.pojo;

// Generated 2009-8-20 4:02:54 by Hibernate Tools 3.2.4.GA

/**
 * RoomParty generated by hbm2java
 */
public class RoomParty implements java.io.Serializable {

	private Integer roomPartyId;
	private String roomId;
	private String partyId;

	public RoomParty() {
	}

	public RoomParty(String partyId) {
		this.partyId = partyId;
	}

	public RoomParty(String roomId, String partyId) {
		this.roomId = roomId;
		this.partyId = partyId;
	}

	public Integer getRoomPartyId() {
		return this.roomPartyId;
	}

	public void setRoomPartyId(Integer roomPartyId) {
		this.roomPartyId = roomPartyId;
	}

	public String getRoomId() {
		return this.roomId;
	}

	public void setRoomId(String roomId) {
		this.roomId = roomId;
	}

	public String getPartyId() {
		return this.partyId;
	}

	public void setPartyId(String partyId) {
		this.partyId = partyId;
	}

}
