package com.cma.intervideo.pojo;

// Generated 2009-10-2 19:10:14 by Hibernate Tools 3.2.4.GA

/**
 * Unit generated by hbm2java
 */
public class Unit implements java.io.Serializable {

	private Integer unitId;
	private String unitName;
	private String partyId;
	private String desc;

	public Unit() {
	}

	public Unit(String unitName) {
		this.unitName = unitName;
	}

	public Unit(String unitName, String partyId, String desc) {
		this.unitName = unitName;
		this.partyId = partyId;
		this.desc = desc;
	}

	public Integer getUnitId() {
		return this.unitId;
	}

	public void setUnitId(Integer unitId) {
		this.unitId = unitId;
	}

	

	public String getUnitName() {
		return unitName;
	}

	public void setUnitName(String unitName) {
		this.unitName = unitName;
	}

	public String getPartyId() {
		return this.partyId;
	}

	public void setPartyId(String partyId) {
		this.partyId = partyId;
	}

	public String getDesc() {
		return this.desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

}
