package com.cma.intervideo.pojo;

// Generated 2009-10-2 19:10:14 by Hibernate Tools 3.2.4.GA

/**
 * Unit generated by hbm2java
 */
public class Unit implements java.io.Serializable {

	private Integer unitId;
	private int uniName;
	private String partyId;
	private String desc;

	public Unit() {
	}

	public Unit(int uniName) {
		this.uniName = uniName;
	}

	public Unit(int uniName, String partyId, String desc) {
		this.uniName = uniName;
		this.partyId = partyId;
		this.desc = desc;
	}

	public Integer getUnitId() {
		return this.unitId;
	}

	public void setUnitId(Integer unitId) {
		this.unitId = unitId;
	}

	public int getUniName() {
		return this.uniName;
	}

	public void setUniName(int uniName) {
		this.uniName = uniName;
	}

	public String getPartyId() {
		return this.partyId;
	}

	public void setPartyId(String partyId) {
		this.partyId = partyId;
	}

	public String getDesc() {
		return this.desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

}
