package com.cma.intervideo.pojo;

// Generated 2009-8-20 4:02:54 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * BulletinBoard generated by hbm2java
 */
public class BulletinBoard implements java.io.Serializable {

	private Integer bulletinId;
	private String userId;
	private String title;
	private String content;
	private Date effectiveTime;
	private Date expiredTime;
	private Date createTime;
	private Date updateTime;
	private Short status;
	private String loginId;
	public BulletinBoard() {
	}

	public BulletinBoard(String title, Date effectiveTime, Date createTime,
			Date updateTime, Short status) {
		this.title = title;
		this.effectiveTime = effectiveTime;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.status = status;
	}

	public BulletinBoard(String userId, String title, String content,
			Date effectiveTime, Date expiredTime, Date createTime,
			Date updateTime, Short status) {
		this.userId = userId;
		this.title = title;
		this.content = content;
		this.effectiveTime = effectiveTime;
		this.expiredTime = expiredTime;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.status = status;
	}

	public Integer getBulletinId() {
		return this.bulletinId;
	}

	public void setBulletinId(Integer bulletinId) {
		this.bulletinId = bulletinId;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getEffectiveTime() {
		return this.effectiveTime;
	}

	public void setEffectiveTime(Date effectiveTime) {
		this.effectiveTime = effectiveTime;
	}

	public Date getExpiredTime() {
		return this.expiredTime;
	}

	public void setExpiredTime(Date expiredTime) {
		this.expiredTime = expiredTime;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public Short getStatus() {
		return this.status;
	}

	public void setStatus(Short status) {
		this.status = status;
	}

	public String getLoginId() {
		return loginId;
	}

	public void setLoginId(String loginId) {
		this.loginId = loginId;
	}
	
	

}
