package com.cma.intervideo.pojo;

// Generated 2009-8-20 4:02:54 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * Conference generated by hbm2java
 */
public class Conference implements java.io.Serializable {

	private Integer conferenceId;
	private String roomId;
	private String userId;
	private String radConferenceId;
	private String dialableNumber;
	private String virtualConfId;
	private Long startTime;
	private Long endTime;
	private String serviceTemplate;
	private String memberId;
	private String description;
	private String password;
	private String controlPin;
	private byte status;
	private Integer portsNum;
	private String subject;
	private Date createTime;
	private Date cancelTime;
	private Date updateTime;
	private String cancelReason;

	public Conference() {
	}

	public Conference(byte status, String subject, Date createTime,
			Date updateTime) {
		this.status = status;
		this.subject = subject;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	public Conference(String roomId, String userId, String radConferenceId,
			String dialableNumber, String virtualConfId, Long startTime,
			Long endTime, String serviceTemplate, String memberId,
			String description, String password, String controlPin,
			byte status, Integer portsNum, String subject, Date createTime,
			Date cancelTime, Date updateTime, String cancelReason) {
		this.roomId = roomId;
		this.userId = userId;
		this.radConferenceId = radConferenceId;
		this.dialableNumber = dialableNumber;
		this.virtualConfId = virtualConfId;
		this.startTime = startTime;
		this.endTime = endTime;
		this.serviceTemplate = serviceTemplate;
		this.memberId = memberId;
		this.description = description;
		this.password = password;
		this.controlPin = controlPin;
		this.status = status;
		this.portsNum = portsNum;
		this.subject = subject;
		this.createTime = createTime;
		this.cancelTime = cancelTime;
		this.updateTime = updateTime;
		this.cancelReason = cancelReason;
	}

	public Integer getConferenceId() {
		return this.conferenceId;
	}

	public void setConferenceId(Integer conferenceId) {
		this.conferenceId = conferenceId;
	}

	public String getRoomId() {
		return this.roomId;
	}

	public void setRoomId(String roomId) {
		this.roomId = roomId;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getRadConferenceId() {
		return this.radConferenceId;
	}

	public void setRadConferenceId(String radConferenceId) {
		this.radConferenceId = radConferenceId;
	}

	public String getDialableNumber() {
		return this.dialableNumber;
	}

	public void setDialableNumber(String dialableNumber) {
		this.dialableNumber = dialableNumber;
	}

	public String getVirtualConfId() {
		return this.virtualConfId;
	}

	public void setVirtualConfId(String virtualConfId) {
		this.virtualConfId = virtualConfId;
	}

	public Long getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Long startTime) {
		this.startTime = startTime;
	}

	public Long getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Long endTime) {
		this.endTime = endTime;
	}

	public String getServiceTemplate() {
		return this.serviceTemplate;
	}

	public void setServiceTemplate(String serviceTemplate) {
		this.serviceTemplate = serviceTemplate;
	}

	public String getMemberId() {
		return this.memberId;
	}

	public void setMemberId(String memberId) {
		this.memberId = memberId;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getControlPin() {
		return this.controlPin;
	}

	public void setControlPin(String controlPin) {
		this.controlPin = controlPin;
	}

	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

	public Integer getPortsNum() {
		return this.portsNum;
	}

	public void setPortsNum(Integer portsNum) {
		this.portsNum = portsNum;
	}

	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getCancelTime() {
		return this.cancelTime;
	}

	public void setCancelTime(Date cancelTime) {
		this.cancelTime = cancelTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getCancelReason() {
		return this.cancelReason;
	}

	public void setCancelReason(String cancelReason) {
		this.cancelReason = cancelReason;
	}

}
