package com.cma.intervideo.pojo;

// Generated 2009-8-20 4:02:54 by Hibernate Tools 3.2.4.GA

/**
 * ConfParty generated by hbm2java
 */
public class ConfParty implements java.io.Serializable {

	private Integer confPartyId;
	private int conferenceId;
	private String partyId;

	public ConfParty() {
	}

	public ConfParty(int conferenceId, String partyId) {
		this.conferenceId = conferenceId;
		this.partyId = partyId;
	}

	public Integer getConfPartyId() {
		return this.confPartyId;
	}

	public void setConfPartyId(Integer confPartyId) {
		this.confPartyId = confPartyId;
	}

	public int getConferenceId() {
		return this.conferenceId;
	}

	public void setConferenceId(int conferenceId) {
		this.conferenceId = conferenceId;
	}

	public String getPartyId() {
		return this.partyId;
	}

	public void setPartyId(String partyId) {
		this.partyId = partyId;
	}

}
