package com.cma.intervideo.pojo;

// Generated Dec 3, 2009 12:43:06 AM by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * ConfTemplate generated by hbm2java
 */
public class ConfTemplate implements java.io.Serializable {

	private int confTemplateId;
	private String confTemplateName;
	private String userId;
	private String serviceTemplateId;
	private String virtualConfId;
	private Integer timeLong;
	private String memberId;
	private String description;
	private String password;
	private String controlPin;
	private Short status;
	private Integer portsNum;
	private String subject;
	private Date createTime;
	private Date deleteTime;
	private String initUnit;
	private Integer mainUnit;
	private String presider;
	private String principalMobile;
	private String reserveCode;
	private String contactMethod;
	private String principal;
	private Boolean isDefault;
	private String serviceTemplateName; // additional property
	private String serviceTemplateDesc; //additional property
	private String confUnitNames; //added additional
	private String mainUnitName; //added additional

	public ConfTemplate() {
	}

	public ConfTemplate(int confTemplateId, String confTemplateName,
			String userId, String memberId) {
		this.confTemplateId = confTemplateId;
		this.confTemplateName = confTemplateName;
		this.userId = userId;
		this.memberId = memberId;
	}

	public ConfTemplate(int confTemplateId, String confTemplateName,
			String userId, String serviceTemplateId, String virtualConfId,
			Integer timeLong, String memberId, String description,
			String password, String controlPin, Short status, Integer portsNum,
			String subject, Date createTime, Date deleteTime, String initUnit,
			Integer mainUnit, String presider, String principalMobile,
			String reserveCode, String contactMethod, String principal,
			Boolean isDefault) {
		this.confTemplateId = confTemplateId;
		this.confTemplateName = confTemplateName;
		this.userId = userId;
		this.serviceTemplateId = serviceTemplateId;
		this.virtualConfId = virtualConfId;
		this.timeLong = timeLong;
		this.memberId = memberId;
		this.description = description;
		this.password = password;
		this.controlPin = controlPin;
		this.status = status;
		this.portsNum = portsNum;
		this.subject = subject;
		this.createTime = createTime;
		this.deleteTime = deleteTime;
		this.initUnit = initUnit;
		this.mainUnit = mainUnit;
		this.presider = presider;
		this.principalMobile = principalMobile;
		this.reserveCode = reserveCode;
		this.contactMethod = contactMethod;
		this.principal = principal;
		this.isDefault = isDefault;
	}

	public int getConfTemplateId() {
		return this.confTemplateId;
	}

	public void setConfTemplateId(int confTemplateId) {
		this.confTemplateId = confTemplateId;
	}

	public String getConfTemplateName() {
		return this.confTemplateName;
	}

	public void setConfTemplateName(String confTemplateName) {
		this.confTemplateName = confTemplateName;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getServiceTemplateId() {
		return this.serviceTemplateId;
	}

	public void setServiceTemplateId(String serviceTemplateId) {
		this.serviceTemplateId = serviceTemplateId;
	}

	public String getVirtualConfId() {
		return this.virtualConfId;
	}

	public void setVirtualConfId(String virtualConfId) {
		this.virtualConfId = virtualConfId;
	}

	public Integer getTimeLong() {
		return this.timeLong;
	}

	public void setTimeLong(Integer timeLong) {
		this.timeLong = timeLong;
	}

	public String getMemberId() {
		return this.memberId;
	}

	public void setMemberId(String memberId) {
		this.memberId = memberId;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getControlPin() {
		return this.controlPin;
	}

	public void setControlPin(String controlPin) {
		this.controlPin = controlPin;
	}

	public Short getStatus() {
		return this.status;
	}

	public void setStatus(Short status) {
		this.status = status;
	}

	public Integer getPortsNum() {
		return this.portsNum;
	}

	public void setPortsNum(Integer portsNum) {
		this.portsNum = portsNum;
	}

	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getDeleteTime() {
		return this.deleteTime;
	}

	public void setDeleteTime(Date deleteTime) {
		this.deleteTime = deleteTime;
	}

	public String getInitUnit() {
		return this.initUnit;
	}

	public void setInitUnit(String initUnit) {
		this.initUnit = initUnit;
	}

	public Integer getMainUnit() {
		return this.mainUnit;
	}

	public void setMainUnit(Integer mainUnit) {
		this.mainUnit = mainUnit;
	}

	public String getPresider() {
		return this.presider;
	}

	public void setPresider(String presider) {
		this.presider = presider;
	}

	public String getPrincipalMobile() {
		return this.principalMobile;
	}

	public void setPrincipalMobile(String principalMobile) {
		this.principalMobile = principalMobile;
	}

	public String getReserveCode() {
		return this.reserveCode;
	}

	public void setReserveCode(String reserveCode) {
		this.reserveCode = reserveCode;
	}

	public String getContactMethod() {
		return this.contactMethod;
	}

	public void setContactMethod(String contactMethod) {
		this.contactMethod = contactMethod;
	}

	public String getPrincipal() {
		return this.principal;
	}

	public void setPrincipal(String principal) {
		this.principal = principal;
	}

	public Boolean getIsDefault() {
		return this.isDefault;
	}

	public void setIsDefault(Boolean isDefault) {
		this.isDefault = isDefault;
	}

	public String getServiceTemplateName() {
		return serviceTemplateName;
	}

	public void setServiceTemplateName(String serviceTemplateName) {
		this.serviceTemplateName = serviceTemplateName;
	}

	public String getServiceTemplateDesc() {
		return serviceTemplateDesc;
	}

	public void setServiceTemplateDesc(String serviceTemplateDesc) {
		this.serviceTemplateDesc = serviceTemplateDesc;
	}

	public String getConfUnitNames() {
		return confUnitNames;
	}

	public void setConfUnitNames(String confUnitNames) {
		this.confUnitNames = confUnitNames;
	}
	
	public String getMainUnitName() {
		return mainUnitName;
	}

	public void setMainUnitName(String mainUnitName) {
		this.mainUnitName = mainUnitName;
	}

}
