package com.cma.intervideo.pojo;

// Generated Dec 3, 2009 12:43:06 AM by Hibernate Tools 3.2.4.GA

/**
 * ConfTemplateXUnit generated by hbm2java
 */
public class ConfTemplateXUnit implements java.io.Serializable {

	private Integer confTemplateUnitId;
	private Integer confTemplateId;
	private Integer unitId;

	public String toString()
	{
		StringBuilder buf = new StringBuilder();
		
		String line = System.getProperty("line.separator");
		buf.append(line + "[ConfTemplateXUnit:( @" + hashCode() + ")" + line);
		buf.append(" confTemplateUnitId = " + confTemplateUnitId + ", confTemplateId = " + confTemplateId + ", unitId = " + unitId + line);
		buf.append("]." + line);
		return buf.toString();
	}
	
	public ConfTemplateXUnit() {
	}

	public ConfTemplateXUnit(Integer confTemplateId, Integer uniId) {
		this.confTemplateId = confTemplateId;
		this.unitId = uniId;
	}

	public Integer getConfTemplateUnitId() {
		return this.confTemplateUnitId;
	}

	public void setConfTemplateUnitId(Integer confTemplateUnitId) {
		this.confTemplateUnitId = confTemplateUnitId;
	}

	public Integer getConfTemplateId() {
		return this.confTemplateId;
	}

	public void setConfTemplateId(Integer confTemplateId) {
		this.confTemplateId = confTemplateId;
	}

	public Integer getUnitId() {
		return this.unitId;
	}

	public void setUnitId(Integer unitId) {
		this.unitId = unitId;
	}

}
