package com.cma.intervideo.pojo;

// Generated Dec 3, 2009 12:43:06 AM by Hibernate Tools 3.2.4.GA

/**
 * ConfTemplateXUnit generated by hbm2java
 */
public class ConfTemplateXUnit implements java.io.Serializable {

	private Integer confTemplateUnitId;
	private Integer conConfTemplateId;
	private Integer uniUnitId;

	public ConfTemplateXUnit() {
	}

	public ConfTemplateXUnit(Integer conConfTemplateId, Integer uniUnitId) {
		this.conConfTemplateId = conConfTemplateId;
		this.uniUnitId = uniUnitId;
	}

	public Integer getConfTemplateUnitId() {
		return this.confTemplateUnitId;
	}

	public void setConfTemplateUnitId(Integer confTemplateUnitId) {
		this.confTemplateUnitId = confTemplateUnitId;
	}

	public Integer getConConfTemplateId() {
		return this.conConfTemplateId;
	}

	public void setConConfTemplateId(Integer conConfTemplateId) {
		this.conConfTemplateId = conConfTemplateId;
	}

	public Integer getUniUnitId() {
		return this.uniUnitId;
	}

	public void setUniUnitId(Integer uniUnitId) {
		this.uniUnitId = uniUnitId;
	}

}
