package com.cma.intervideo.pojo;

// Generated 2009-8-20 4:02:54 by Hibernate Tools 3.2.4.GA

/**
 * FieldDescId generated by hbm2java
 */
public class FieldDescId implements java.io.Serializable {

	private String tableName;
	private String fieldName;
	private int fieldValue;
	private String fieldDesc;

	public FieldDescId() {
	}

	public FieldDescId(String tableName, String fieldName, int fieldValue,
			String fieldDesc) {
		this.tableName = tableName;
		this.fieldName = fieldName;
		this.fieldValue = fieldValue;
		this.fieldDesc = fieldDesc;
	}

	public String getTableName() {
		return this.tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	public String getFieldName() {
		return this.fieldName;
	}

	public void setFieldName(String fieldName) {
		this.fieldName = fieldName;
	}

	public int getFieldValue() {
		return this.fieldValue;
	}

	public void setFieldValue(int fieldValue) {
		this.fieldValue = fieldValue;
	}

	public String getFieldDesc() {
		return this.fieldDesc;
	}

	public void setFieldDesc(String fieldDesc) {
		this.fieldDesc = fieldDesc;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FieldDescId))
			return false;
		FieldDescId castOther = (FieldDescId) other;

		return ((this.getTableName() == castOther.getTableName()) || (this
				.getTableName() != null
				&& castOther.getTableName() != null && this.getTableName()
				.equals(castOther.getTableName())))
				&& ((this.getFieldName() == castOther.getFieldName()) || (this
						.getFieldName() != null
						&& castOther.getFieldName() != null && this
						.getFieldName().equals(castOther.getFieldName())))
				&& (this.getFieldValue() == castOther.getFieldValue())
				&& ((this.getFieldDesc() == castOther.getFieldDesc()) || (this
						.getFieldDesc() != null
						&& castOther.getFieldDesc() != null && this
						.getFieldDesc().equals(castOther.getFieldDesc())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getTableName() == null ? 0 : this.getTableName().hashCode());
		result = 37 * result
				+ (getFieldName() == null ? 0 : this.getFieldName().hashCode());
		result = 37 * result + this.getFieldValue();
		result = 37 * result
				+ (getFieldDesc() == null ? 0 : this.getFieldDesc().hashCode());
		return result;
	}

}
