package com.cma.intervideo.pojo;

// Generated 2009-8-20 4:02:54 by Hibernate Tools 3.2.4.GA

/**
 * FieldDesc generated by hbm2java
 */
public class FieldDesc implements java.io.Serializable {

	private FieldDescId id;

	public FieldDesc() {
	}

	public FieldDesc(FieldDescId id) {
		this.id = id;
	}

	public FieldDescId getId() {
		return this.id;
	}

	public void setId(FieldDescId id) {
		this.id = id;
	}

}
