package com.cma.intervideo.pojo;

// Generated 2009-8-20 4:02:54 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * Log generated by hbm2java
 */
public class Log implements java.io.Serializable {
	

	private Integer logId;
	private String userId;
	private Short logType;
	private Date createTime;
	private String description;
	private String loginId;
	private String userName;
	public Log() {
	}

	public Log(Short logType, Date createTime) {
		this.logType = logType;
		this.createTime = createTime;
	}

	public Log(String userId, Short logType, Date createTime, String description) {
		this.userId = userId;
		this.logType = logType;
		this.createTime = createTime;
		this.description = description;
	}

	public Integer getLogId() {
		return this.logId;
	}

	public void setLogId(Integer logId) {
		this.logId = logId;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public Short getLogType() {
		return this.logType;
	}

	public void setLogType(Short logType) {
		this.logType = logType;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getLoginId() {
		return loginId;
	}

	public void setLoginId(String loginId) {
		this.loginId = loginId;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}
	
}
