package com.cma.intervideo.pojo;

import java.util.Date;

// Generated 2009-8-20 4:02:54 by Hibernate Tools 3.2.4.GA

/**
 * MessageBoard generated by hbm2java
 */
public class MessageBoard implements java.io.Serializable {

	private Integer messageId;
	private String userId;
	private String title;
	private String content;
	private Short status;
	private Date createTime;
	private String userName; //additional
	private Integer omsgId;
	private Date updateTime;
	
	public MessageBoard() {
	}

	public MessageBoard(Short status) {
		this.status = status;
	}

	
	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public Integer getMessageId() {
		return this.messageId;
	}

	public void setMessageId(Integer messageId) {
		this.messageId = messageId;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Short getStatus() {
		return this.status;
	}

	public void setStatus(Short status) {
		this.status = status;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Integer getOmsgId() {
		return omsgId;
	}

	public void setOmsgId(Integer omsgId) {
		this.omsgId = omsgId;
	}

	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
	
	
}
