package com.cma.intervideo.pojo;

// Generated Jan 17, 2010 1:18:25 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * RecurringMeetingInfo generated by hbm2java
 */
public class RecurringMeetingInfo implements java.io.Serializable {

	public static final short status_upcoming = 0;
	public static final short status_cancel = 3;
	
	public static final int RECURRING_DAILY = 1;
	public static final int RECURRING_WEEKLY = 2;
	public static final int RECURRING_MONTHLY = 3;
	
	public static final int RECURRING_ENDTYPE_DATE = 1;
	public static final int RECURRING_ENDTYPE_NUMBER = 2;

	private Integer recurrenceId;
	private String userId;
	private String serviceTemplateId;
	private Integer confTemplateId;
	private String radRecurrenceId;
	private String dialableNumber;
	private String virtualConfId;
	private Long startTime;
	private Integer timeLong;
	private String memberId;
	private String description;
	private String password;
	private String controlPin;
	private Short status;
	private Integer portsNum;
	private String subject;
	private Date createTime;
	private Date cancelTime;
	private Date updateTime;
	private String cancelReason;
	private String initUnit;
	private Integer mainUnit;
	private String presider;
	private String principalMobile;
	private String reserveCode;
	private String contactMethod;
	private String principal;
	private Short confType;
	private Short isBroadcast;
	private Short isSupport;
	private Short isRecord;
	private Integer recurrenceType;
	private Integer dayInterval;
	private Integer weekInterval;
	private Integer weekDay;
	private Integer monthInterval;
	private Integer monthDay;
	private Long startDate;
	private Integer endType;
	private Long endDate;
	private Integer endAfterNumber;
	
	private String serviceTemplateName; //added additional
	private String serviceTemplateDesc; //added additional
	private String confTypeDesc;
	private String confUnitNames; //added additional
	private String mainUnitName; //added additional

	public RecurringMeetingInfo() {
	}

	public RecurringMeetingInfo(Short status, String subject, Date createTime,
			Date updateTime, Short confType) {
		this.status = status;
		this.subject = subject;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.confType = confType;
	}

	public RecurringMeetingInfo(String userId, String serviceTemplateId,
			Integer confTemplateId, String radRecurrenceId,
			String dialableNumber, String virtualConfId, Long startTime,
			Integer timeLong, String memberId, String description,
			String password, String controlPin, Short status, Integer portsNum,
			String subject, Date createTime, Date cancelTime, Date updateTime,
			String cancelReason, String initUnit, Integer mainUnit,
			String presider, String principalMobile, String reserveCode,
			String contactMethod, String principal, Short confType,
			Short isBroadcast, Short isSupport, Short isRecord,
			Integer recurrenceType, Integer dayInterval, Integer weekInterval,
			Integer weekDay, Integer monthInterval, Integer monthDay,
			Long startDate, Integer endType, Long endDate,
			Integer endAfterNumber) {
		this.userId = userId;
		this.serviceTemplateId = serviceTemplateId;
		this.confTemplateId = confTemplateId;
		this.radRecurrenceId = radRecurrenceId;
		this.dialableNumber = dialableNumber;
		this.virtualConfId = virtualConfId;
		this.startTime = startTime;
		this.timeLong = timeLong;
		this.memberId = memberId;
		this.description = description;
		this.password = password;
		this.controlPin = controlPin;
		this.status = status;
		this.portsNum = portsNum;
		this.subject = subject;
		this.createTime = createTime;
		this.cancelTime = cancelTime;
		this.updateTime = updateTime;
		this.cancelReason = cancelReason;
		this.initUnit = initUnit;
		this.mainUnit = mainUnit;
		this.presider = presider;
		this.principalMobile = principalMobile;
		this.reserveCode = reserveCode;
		this.contactMethod = contactMethod;
		this.principal = principal;
		this.confType = confType;
		this.isBroadcast = isBroadcast;
		this.isSupport = isSupport;
		this.isRecord = isRecord;
		this.recurrenceType = recurrenceType;
		this.dayInterval = dayInterval;
		this.weekInterval = weekInterval;
		this.weekDay = weekDay;
		this.monthInterval = monthInterval;
		this.monthDay = monthDay;
		this.startDate = startDate;
		this.endType = endType;
		this.endDate = endDate;
		this.endAfterNumber = endAfterNumber;
	}

	public Integer getRecurrenceId() {
		return this.recurrenceId;
	}

	public void setRecurrenceId(Integer recurrenceId) {
		this.recurrenceId = recurrenceId;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getServiceTemplateId() {
		return this.serviceTemplateId;
	}

	public void setServiceTemplateId(String serviceTemplateId) {
		this.serviceTemplateId = serviceTemplateId;
	}

	public Integer getConfTemplateId() {
		return this.confTemplateId;
	}

	public void setConfTemplateId(Integer confTemplateId) {
		this.confTemplateId = confTemplateId;
	}

	public String getRadRecurrenceId() {
		return this.radRecurrenceId;
	}

	public void setRadRecurrenceId(String radRecurrenceId) {
		this.radRecurrenceId = radRecurrenceId;
	}

	public String getDialableNumber() {
		return this.dialableNumber;
	}

	public void setDialableNumber(String dialableNumber) {
		this.dialableNumber = dialableNumber;
	}

	public String getVirtualConfId() {
		return this.virtualConfId;
	}

	public void setVirtualConfId(String virtualConfId) {
		this.virtualConfId = virtualConfId;
	}

	public Long getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Long startTime) {
		this.startTime = startTime;
	}

	public Integer getTimeLong() {
		return this.timeLong;
	}

	public void setTimeLong(Integer timeLong) {
		this.timeLong = timeLong;
	}

	public String getMemberId() {
		return this.memberId;
	}

	public void setMemberId(String memberId) {
		this.memberId = memberId;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getControlPin() {
		return this.controlPin;
	}

	public void setControlPin(String controlPin) {
		this.controlPin = controlPin;
	}

	public Short getStatus() {
		return this.status;
	}

	public void setStatus(Short status) {
		this.status = status;
	}

	public Integer getPortsNum() {
		return this.portsNum;
	}

	public void setPortsNum(Integer portsNum) {
		this.portsNum = portsNum;
	}

	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getCancelTime() {
		return this.cancelTime;
	}

	public void setCancelTime(Date cancelTime) {
		this.cancelTime = cancelTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getCancelReason() {
		return this.cancelReason;
	}

	public void setCancelReason(String cancelReason) {
		this.cancelReason = cancelReason;
	}

	public String getInitUnit() {
		return this.initUnit;
	}

	public void setInitUnit(String initUnit) {
		this.initUnit = initUnit;
	}

	public Integer getMainUnit() {
		return this.mainUnit;
	}

	public void setMainUnit(Integer mainUnit) {
		this.mainUnit = mainUnit;
	}

	public String getPresider() {
		return this.presider;
	}

	public void setPresider(String presider) {
		this.presider = presider;
	}

	public String getPrincipalMobile() {
		return this.principalMobile;
	}

	public void setPrincipalMobile(String principalMobile) {
		this.principalMobile = principalMobile;
	}

	public String getReserveCode() {
		return this.reserveCode;
	}

	public void setReserveCode(String reserveCode) {
		this.reserveCode = reserveCode;
	}

	public String getContactMethod() {
		return this.contactMethod;
	}

	public void setContactMethod(String contactMethod) {
		this.contactMethod = contactMethod;
	}

	public String getPrincipal() {
		return this.principal;
	}

	public void setPrincipal(String principal) {
		this.principal = principal;
	}

	public Short getConfType() {
		return this.confType;
	}

	public void setConfType(Short confType) {
		this.confType = confType;
	}

	public Short getIsBroadcast() {
		return this.isBroadcast;
	}

	public void setIsBroadcast(Short isBroadcast) {
		this.isBroadcast = isBroadcast;
	}

	public Short getIsSupport() {
		return this.isSupport;
	}

	public void setIsSupport(Short isSupport) {
		this.isSupport = isSupport;
	}

	public Short getIsRecord() {
		return this.isRecord;
	}

	public void setIsRecord(Short isRecord) {
		this.isRecord = isRecord;
	}

	public Integer getRecurrenceType() {
		return this.recurrenceType;
	}

	public void setRecurrenceType(Integer recurrenceType) {
		this.recurrenceType = recurrenceType;
	}

	public Integer getDayInterval() {
		return this.dayInterval;
	}

	public void setDayInterval(Integer dayInterval) {
		this.dayInterval = dayInterval;
	}

	public Integer getWeekInterval() {
		return this.weekInterval;
	}

	public void setWeekInterval(Integer weekInterval) {
		this.weekInterval = weekInterval;
	}

	public Integer getWeekDay() {
		return this.weekDay;
	}

	public void setWeekDay(Integer weekDay) {
		this.weekDay = weekDay;
	}

	public Integer getMonthInterval() {
		return this.monthInterval;
	}

	public void setMonthInterval(Integer monthInterval) {
		this.monthInterval = monthInterval;
	}

	public Integer getMonthDay() {
		return this.monthDay;
	}

	public void setMonthDay(Integer monthDay) {
		this.monthDay = monthDay;
	}

	public Long getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Long startDate) {
		this.startDate = startDate;
	}

	public Integer getEndType() {
		return this.endType;
	}

	public void setEndType(Integer endType) {
		this.endType = endType;
	}

	public Long getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Long endDate) {
		this.endDate = endDate;
	}

	public Integer getEndAfterNumber() {
		return this.endAfterNumber;
	}

	public void setEndAfterNumber(Integer endAfterNumber) {
		this.endAfterNumber = endAfterNumber;
	}

	public String getConfTypeDesc() {
		return confTypeDesc;
	}

	public void setConfTypeDesc(String confTypeDesc) {
		this.confTypeDesc = confTypeDesc;
	}

	public String getServiceTemplateName() {
		return serviceTemplateName;
	}

	public void setServiceTemplateName(String serviceTemplateName) {
		this.serviceTemplateName = serviceTemplateName;
	}

	public String getServiceTemplateDesc() {
		return serviceTemplateDesc;
	}

	public void setServiceTemplateDesc(String serviceTemplateDesc) {
		this.serviceTemplateDesc = serviceTemplateDesc;
	}

	public String getConfUnitNames() {
		return confUnitNames;
	}

	public void setConfUnitNames(String confUnitNames) {
		this.confUnitNames = confUnitNames;
	}

	public String getMainUnitName() {
		return mainUnitName;
	}

	public void setMainUnitName(String mainUnitName) {
		this.mainUnitName = mainUnitName;
	}

}
