package com.cma.intervideo.pojo;

// Generated Sep 29, 2009 11:53:51 PM by Hibernate Tools 3.2.4.GA

/**
 * ServiceTemplate generated by hbm2java
 */
public class ServiceTemplate implements java.io.Serializable {

	private String serviceTemplateId;
	private String servicePrefix;
	private String serviceTemplateName;
	private Boolean activeFlag;
	private Boolean audioOnly;
	private Boolean slave;
	private Integer matchingRate;
	private Boolean hasSymmetric;
	private Boolean isUploaded;
	private Boolean isFromDevice;
	private Boolean isUploadable;
	private String serviceTemplateDesc;
	private String deviceString;
	private String backup1;
	private String backup2;
	private Character lectureModeSign;
	private String builtInToken;
	private Integer serviceType;
	private Integer switchingMode;
	private Integer isHdGuaranteed;
	private Integer isHdCapable;
	private String ivrPrefix;

	public ServiceTemplate() {
	}

	public ServiceTemplate(String serviceTemplateId) {
		this.serviceTemplateId = serviceTemplateId;
	}

	public ServiceTemplate(String serviceTemplateId, String servicePrefix,
			String serviceTemplateName, Boolean activeFlag, Boolean audioOnly,
			Boolean slave, Integer matchingRate, Boolean hasSymmetric,
			Boolean isUploaded, Boolean isFromDevice, Boolean isUploadable,
			String serviceTemplateDesc, String deviceString, String backup1,
			String backup2, Character lectureModeSign, String builtInToken,
			Integer serviceType, Integer switchingMode, Integer isHdGuaranteed,
			Integer isHdCapable, String ivrPrefix) {
		this.serviceTemplateId = serviceTemplateId;
		this.servicePrefix = servicePrefix;
		this.serviceTemplateName = serviceTemplateName;
		this.activeFlag = activeFlag;
		this.audioOnly = audioOnly;
		this.slave = slave;
		this.matchingRate = matchingRate;
		this.hasSymmetric = hasSymmetric;
		this.isUploaded = isUploaded;
		this.isFromDevice = isFromDevice;
		this.isUploadable = isUploadable;
		this.serviceTemplateDesc = serviceTemplateDesc;
		this.deviceString = deviceString;
		this.backup1 = backup1;
		this.backup2 = backup2;
		this.lectureModeSign = lectureModeSign;
		this.builtInToken = builtInToken;
		this.serviceType = serviceType;
		this.switchingMode = switchingMode;
		this.isHdGuaranteed = isHdGuaranteed;
		this.isHdCapable = isHdCapable;
		this.ivrPrefix = ivrPrefix;
	}

	public String getServiceTemplateId() {
		return this.serviceTemplateId;
	}

	public void setServiceTemplateId(String serviceTemplateId) {
		this.serviceTemplateId = serviceTemplateId;
	}

	public String getServicePrefix() {
		return this.servicePrefix;
	}

	public void setServicePrefix(String servicePrefix) {
		this.servicePrefix = servicePrefix;
	}

	public String getServiceTemplateName() {
		return this.serviceTemplateName;
	}

	public void setServiceTemplateName(String serviceTemplateName) {
		this.serviceTemplateName = serviceTemplateName;
	}

	public Boolean getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(Boolean activeFlag) {
		this.activeFlag = activeFlag;
	}

	public Boolean getAudioOnly() {
		return this.audioOnly;
	}

	public void setAudioOnly(Boolean audioOnly) {
		this.audioOnly = audioOnly;
	}

	public Boolean getSlave() {
		return this.slave;
	}

	public void setSlave(Boolean slave) {
		this.slave = slave;
	}

	public Integer getMatchingRate() {
		return this.matchingRate;
	}

	public void setMatchingRate(Integer matchingRate) {
		this.matchingRate = matchingRate;
	}

	public Boolean getHasSymmetric() {
		return this.hasSymmetric;
	}

	public void setHasSymmetric(Boolean hasSymmetric) {
		this.hasSymmetric = hasSymmetric;
	}

	public Boolean getIsUploaded() {
		return this.isUploaded;
	}

	public void setIsUploaded(Boolean isUploaded) {
		this.isUploaded = isUploaded;
	}

	public Boolean getIsFromDevice() {
		return this.isFromDevice;
	}

	public void setIsFromDevice(Boolean isFromDevice) {
		this.isFromDevice = isFromDevice;
	}

	public Boolean getIsUploadable() {
		return this.isUploadable;
	}

	public void setIsUploadable(Boolean isUploadable) {
		this.isUploadable = isUploadable;
	}

	public String getServiceTemplateDesc() {
		return this.serviceTemplateDesc;
	}

	public void setServiceTemplateDesc(String serviceTemplateDesc) {
		this.serviceTemplateDesc = serviceTemplateDesc;
	}

	public String getDeviceString() {
		return this.deviceString;
	}

	public void setDeviceString(String deviceString) {
		this.deviceString = deviceString;
	}

	public String getBackup1() {
		return this.backup1;
	}

	public void setBackup1(String backup1) {
		this.backup1 = backup1;
	}

	public String getBackup2() {
		return this.backup2;
	}

	public void setBackup2(String backup2) {
		this.backup2 = backup2;
	}

	public Character getLectureModeSign() {
		return this.lectureModeSign;
	}

	public void setLectureModeSign(Character lectureModeSign) {
		this.lectureModeSign = lectureModeSign;
	}

	public String getBuiltInToken() {
		return this.builtInToken;
	}

	public void setBuiltInToken(String builtInToken) {
		this.builtInToken = builtInToken;
	}

	public Integer getServiceType() {
		return this.serviceType;
	}

	public void setServiceType(Integer serviceType) {
		this.serviceType = serviceType;
	}

	public Integer getSwitchingMode() {
		return this.switchingMode;
	}

	public void setSwitchingMode(Integer switchingMode) {
		this.switchingMode = switchingMode;
	}

	public Integer getIsHdGuaranteed() {
		return this.isHdGuaranteed;
	}

	public void setIsHdGuaranteed(Integer isHdGuaranteed) {
		this.isHdGuaranteed = isHdGuaranteed;
	}

	public Integer getIsHdCapable() {
		return this.isHdCapable;
	}

	public void setIsHdCapable(Integer isHdCapable) {
		this.isHdCapable = isHdCapable;
	}

	public String getIvrPrefix() {
		return this.ivrPrefix;
	}

	public void setIvrPrefix(String ivrPrefix) {
		this.ivrPrefix = ivrPrefix;
	}

}
