package com.cma.intervideo.pojo;

// Generated Oct 2, 2009 10:01:01 PM by Hibernate Tools 3.2.4.GA

/**
 * Terminal generated by hbm2java
 */
public class Terminal implements java.io.Serializable {

	private String terminalId;
	private String terminalName;
	private String terminalNumber;
	private short terminalProtocol;
	private String timeZoneId;
	private String zonePrefix;
	private String terminalEmail;
	private Boolean statusId;
	private String registerGkid;
	private String nodeId;
	private Integer maxBandwidth;
	private Integer isdnMaxBandwidth;
	private Boolean isVoiceOnly;
	private String ip;
	private String e164;
	private Short detailProtocol;
	private String defaultRoomId;
	private String countryCode;
	private String areaCode;

	public String toString() {
		StringBuilder buf = new StringBuilder();
		
		String line = System.getProperty("line.separator");
		buf.append(line + "[Terminal:( @" + hashCode() + ")" + line);
		buf.append(" terminalId = " + terminalId + ", terminalName = " + terminalName + line);
		buf.append(" terminalNumber = " + terminalNumber + ", terminalProtocol = " + terminalProtocol + line);
		buf.append(" timeZoneId = " + timeZoneId + ", zonePrefix = " + zonePrefix + line);
		buf.append(" terminalEmail = " + terminalEmail + ", statusId = " + statusId + line);
		buf.append(" registerGkid = " + registerGkid + ", nodeId = " + nodeId + line);
		buf.append(" maxBandwidth = " + maxBandwidth + ", isdnMaxBandwidth = " + isdnMaxBandwidth + line);
		buf.append(" isVoiceOnly = " + isVoiceOnly + ", ip = " + ip + line);
		buf.append(" e164 = " + e164 + ", detailProtocol = " + detailProtocol + line);
		buf.append(" defaultRoomId = " + defaultRoomId + ", countryCode = " + countryCode + ", areaCode = " + areaCode + line);
		buf.append("]." + line);
		return buf.toString();
	}
	
	public Terminal() {
	}

	public Terminal(String terminalId, short terminalProtocol) {
		this.terminalId = terminalId;
		this.terminalProtocol = terminalProtocol;
	}

	public Terminal(String terminalId, String terminalName,
			String terminalNumber, short terminalProtocol, String timeZoneId,
			String zonePrefix, String terminalEmail, Boolean statusId,
			String registerGkid, String nodeId, Integer maxBandwidth,
			Integer isdnMaxBandwidth, Boolean isVoiceOnly, String ip,
			String e164, Short detailProtocol, String defaultRoomId,
			String countryCode, String areaCode) {
		this.terminalId = terminalId;
		this.terminalName = terminalName;
		this.terminalNumber = terminalNumber;
		this.terminalProtocol = terminalProtocol;
		this.timeZoneId = timeZoneId;
		this.zonePrefix = zonePrefix;
		this.terminalEmail = terminalEmail;
		this.statusId = statusId;
		this.registerGkid = registerGkid;
		this.nodeId = nodeId;
		this.maxBandwidth = maxBandwidth;
		this.isdnMaxBandwidth = isdnMaxBandwidth;
		this.isVoiceOnly = isVoiceOnly;
		this.ip = ip;
		this.e164 = e164;
		this.detailProtocol = detailProtocol;
		this.defaultRoomId = defaultRoomId;
		this.countryCode = countryCode;
		this.areaCode = areaCode;
	}

	public String getTerminalId() {
		return this.terminalId;
	}

	public void setTerminalId(String terminalId) {
		this.terminalId = terminalId;
	}

	public String getTerminalName() {
		return this.terminalName;
	}

	public void setTerminalName(String terminalName) {
		this.terminalName = terminalName;
	}

	public String getTerminalNumber() {
		return this.terminalNumber;
	}

	public void setTerminalNumber(String terminalNumber) {
		this.terminalNumber = terminalNumber;
	}

	public short getTerminalProtocol() {
		return this.terminalProtocol;
	}

	public void setTerminalProtocol(short terminalProtocol) {
		this.terminalProtocol = terminalProtocol;
	}

	public String getTimeZoneId() {
		return this.timeZoneId;
	}

	public void setTimeZoneId(String timeZoneId) {
		this.timeZoneId = timeZoneId;
	}

	public String getZonePrefix() {
		return this.zonePrefix;
	}

	public void setZonePrefix(String zonePrefix) {
		this.zonePrefix = zonePrefix;
	}

	public String getTerminalEmail() {
		return this.terminalEmail;
	}

	public void setTerminalEmail(String terminalEmail) {
		this.terminalEmail = terminalEmail;
	}

	public Boolean getStatusId() {
		return this.statusId;
	}

	public void setStatusId(Boolean statusId) {
		this.statusId = statusId;
	}

	public String getRegisterGkid() {
		return this.registerGkid;
	}

	public void setRegisterGkid(String registerGkid) {
		this.registerGkid = registerGkid;
	}

	public String getNodeId() {
		return this.nodeId;
	}

	public void setNodeId(String nodeId) {
		this.nodeId = nodeId;
	}

	public Integer getMaxBandwidth() {
		return this.maxBandwidth;
	}

	public void setMaxBandwidth(Integer maxBandwidth) {
		this.maxBandwidth = maxBandwidth;
	}

	public Integer getIsdnMaxBandwidth() {
		return this.isdnMaxBandwidth;
	}

	public void setIsdnMaxBandwidth(Integer isdnMaxBandwidth) {
		this.isdnMaxBandwidth = isdnMaxBandwidth;
	}

	public Boolean getIsVoiceOnly() {
		return this.isVoiceOnly;
	}

	public void setIsVoiceOnly(Boolean isVoiceOnly) {
		this.isVoiceOnly = isVoiceOnly;
	}

	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public String getE164() {
		return this.e164;
	}

	public void setE164(String e164) {
		this.e164 = e164;
	}

	public Short getDetailProtocol() {
		return this.detailProtocol;
	}

	public void setDetailProtocol(Short detailProtocol) {
		this.detailProtocol = detailProtocol;
	}

	public String getDefaultRoomId() {
		return this.defaultRoomId;
	}

	public void setDefaultRoomId(String defaultRoomId) {
		this.defaultRoomId = defaultRoomId;
	}

	public String getCountryCode() {
		return this.countryCode;
	}

	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
	}

	public String getAreaCode() {
		return this.areaCode;
	}

	public void setAreaCode(String areaCode) {
		this.areaCode = areaCode;
	}
	
	public String getDialString() {
		if (getTerminalProtocol() == 0)	{ // IP
			if (e164 != null && e164.length() > 0)
				return e164;
			else
				return ip;
		}
		else if (getTerminalProtocol() == 1) //ISDN
			return getCountryCode() + " " +  getAreaCode() + " " + getTerminalNumber();
		else // SIP and others
			return getTerminalNumber();
	}
	
	public String getProtocolDesc() {
		if (getTerminalProtocol() == 0)	// IP
			return "IP";
		else if (getTerminalProtocol() == 1)	// ISDN
			return "ISDN";
		else if (getTerminalProtocol() == 2)	// DUAL
			return "Daul";
		else if (getTerminalProtocol() == 3)	// SIP
			return "SIP";
		else
			return "Unknown";
	}
}
