
package com.radvision.icm.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.1-02/02/2007 03:56 AM(vivekp)-FCS
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ControlService", targetNamespace = "http://radvision.com/icm/service/controlservice", wsdlLocation = "file:/D:/Radvision/Product/icmservice/training/wsimport/wsdl/ControlService.wsdl")
public class ControlService
    extends Service
{

    private final static URL CONTROLSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("file:/D:/Radvision/Product/icmservice/training/wsimport/wsdl/ControlService.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        CONTROLSERVICE_WSDL_LOCATION = url;
    }

    public ControlService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ControlService() {
        super(CONTROLSERVICE_WSDL_LOCATION, new QName("http://radvision.com/icm/service/controlservice", "ControlService"));
    }

    /**
     * 
     * @return
     *     returns ControlServicePortType
     */
    @WebEndpoint(name = "ControlServicePort")
    public ControlServicePortType getControlServicePort() {
        return (ControlServicePortType)super.getPort(new QName("http://radvision.com/icm/service/controlservice", "ControlServicePort"), ControlServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ControlServicePortType
     */
    @WebEndpoint(name = "ControlServicePort")
    public ControlServicePortType getControlServicePort(WebServiceFeature... features) {
        return (ControlServicePortType)super.getPort(new QName("http://radvision.com/icm/service/controlservice", "ControlServicePort"), ControlServicePortType.class, features);
    }

}
