
package com.radvision.icm.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.1-02/02/2007 03:56 AM(vivekp)-FCS
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "LicenseService", targetNamespace = "http://radvision.com/icm/service/licenseservice", wsdlLocation = "file:/D:/Radvision/Product/icmservice/training/wsimport/wsdl/LicenseService.wsdl")
public class LicenseService
    extends Service
{

    private final static URL LICENSESERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("file:/D:/Radvision/Product/icmservice/training/wsimport/wsdl/LicenseService.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        LICENSESERVICE_WSDL_LOCATION = url;
    }

    public LicenseService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LicenseService() {
        super(LICENSESERVICE_WSDL_LOCATION, new QName("http://radvision.com/icm/service/licenseservice", "LicenseService"));
    }

    /**
     * 
     * @return
     *     returns LicenseServicePortType
     */
    @WebEndpoint(name = "LicenseServicePort")
    public LicenseServicePortType getLicenseServicePort() {
        return (LicenseServicePortType)super.getPort(new QName("http://radvision.com/icm/service/licenseservice", "LicenseServicePort"), LicenseServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LicenseServicePortType
     */
    @WebEndpoint(name = "LicenseServicePort")
    public LicenseServicePortType getLicenseServicePort(WebServiceFeature... features) {
        return (LicenseServicePortType)super.getPort(new QName("http://radvision.com/icm/service/licenseservice", "LicenseServicePort"), LicenseServicePortType.class, features);
    }

}
