
package com.radvision.icm.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.1-02/02/2007 03:56 AM(vivekp)-FCS
 * Generated source version: 2.1
 * 
 */
@WebService(name = "LicenseServicePortType", targetNamespace = "http://radvision.com/icm/service/licenseservice")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LicenseServicePortType {


    /**
     * 
     * @param capacityStr
     * @throws CapacityException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "setConcurrentCapacity", targetNamespace = "http://radvision.com/icm/service/licenseservice", className = "com.radvision.icm.service.SetConcurrentCapacity")
    @ResponseWrapper(localName = "setConcurrentCapacityResponse", targetNamespace = "http://radvision.com/icm/service/licenseservice", className = "com.radvision.icm.service.SetConcurrentCapacityResponse")
    public void setConcurrentCapacity(
        @WebParam(name = "capacityStr", targetNamespace = "")
        String capacityStr)
        throws CapacityException_Exception
    ;

}
