
package com.radvision.icm.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.1-02/02/2007 03:56 AM(vivekp)-FCS
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "MoreClassificationsFoundException", targetNamespace = "http://radvision.com/icm/service/resourceservice")
public class MoreClassificationsFoundException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private MoreClassificationsFoundException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public MoreClassificationsFoundException_Exception(String message, MoreClassificationsFoundException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param message
     * @param cause
     */
    public MoreClassificationsFoundException_Exception(String message, MoreClassificationsFoundException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.radvision.icm.service.MoreClassificationsFoundException
     */
    public MoreClassificationsFoundException getFaultInfo() {
        return faultInfo;
    }

}
