
package com.radvision.icm.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.1-02/02/2007 03:56 AM(vivekp)-FCS
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ResourceServicePortType", targetNamespace = "http://radvision.com/icm/service/resourceservice")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ResourceServicePortType {


    /**
     * 
     * @param netClassificationName
     * @return
     *     returns java.util.List<com.radvision.icm.service.TerminalResource>
     * @throws NoClassificationFoundException_Exception
     * @throws InvalidArgumentException_Exception
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getTerminals", targetNamespace = "http://radvision.com/icm/service/resourceservice", className = "com.radvision.icm.service.GetTerminals")
    @ResponseWrapper(localName = "getTerminalsResponse", targetNamespace = "http://radvision.com/icm/service/resourceservice", className = "com.radvision.icm.service.GetTerminalsResponse")
    public List<TerminalResource> getTerminals(
        @WebParam(name = "netClassificationName", targetNamespace = "")
        String netClassificationName)
        throws InvalidArgumentException_Exception, NoClassificationFoundException_Exception
    ;

    /**
     * 
     * @param overwritten
     * @param terminals
     * @return
     *     returns com.radvision.icm.service.ResourceResult
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "setTerminals", targetNamespace = "http://radvision.com/icm/service/resourceservice", className = "com.radvision.icm.service.SetTerminals")
    @ResponseWrapper(localName = "setTerminalsResponse", targetNamespace = "http://radvision.com/icm/service/resourceservice", className = "com.radvision.icm.service.SetTerminalsResponse")
    public ResourceResult setTerminals(
        @WebParam(name = "terminals", targetNamespace = "")
        List<TerminalResource> terminals,
        @WebParam(name = "overwritten", targetNamespace = "")
        boolean overwritten);

    /**
     * 
     * @return
     *     returns java.util.List<com.radvision.icm.service.RoomResource>
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getRooms", targetNamespace = "http://radvision.com/icm/service/resourceservice", className = "com.radvision.icm.service.GetRooms")
    @ResponseWrapper(localName = "getRoomsResponse", targetNamespace = "http://radvision.com/icm/service/resourceservice", className = "com.radvision.icm.service.GetRoomsResponse")
    public List<RoomResource> getRooms();

    /**
     * 
     * @return
     *     returns com.radvision.icm.service.DeviceControllerIpPort
     * @throws NoClassificationFoundException_Exception
     * @throws MoreClassificationsFoundException_Exception
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getDeviceControllerIpPort", targetNamespace = "http://radvision.com/icm/service/resourceservice", className = "com.radvision.icm.service.GetDeviceControllerIpPort")
    @ResponseWrapper(localName = "getDeviceControllerIpPortResponse", targetNamespace = "http://radvision.com/icm/service/resourceservice", className = "com.radvision.icm.service.GetDeviceControllerIpPortResponse")
    public DeviceControllerIpPort getDeviceControllerIpPort()
        throws MoreClassificationsFoundException_Exception, NoClassificationFoundException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.radvision.icm.service.MeetingType>
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getMeetingTypes", targetNamespace = "http://radvision.com/icm/service/resourceservice", className = "com.radvision.icm.service.GetMeetingTypes")
    @ResponseWrapper(localName = "getMeetingTypesResponse", targetNamespace = "http://radvision.com/icm/service/resourceservice", className = "com.radvision.icm.service.GetMeetingTypesResponse")
    public List<MeetingType> getMeetingTypes();

    /**
     * 
     * @param terminalIds
     * @return
     *     returns com.radvision.icm.service.ResourceResult
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "deleteTerminals", targetNamespace = "http://radvision.com/icm/service/resourceservice", className = "com.radvision.icm.service.DeleteTerminals")
    @ResponseWrapper(localName = "deleteTerminalsResponse", targetNamespace = "http://radvision.com/icm/service/resourceservice", className = "com.radvision.icm.service.DeleteTerminalsResponse")
    public ResourceResult deleteTerminals(
        @WebParam(name = "terminalIds", targetNamespace = "")
        List<String> terminalIds);

    /**
     * 
     * @param terminalIds
     * @return
     *     returns java.util.List<com.radvision.icm.service.TerminalResource>
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getTerminalsByIds", targetNamespace = "http://radvision.com/icm/service/resourceservice", className = "com.radvision.icm.service.GetTerminalsByIds")
    @ResponseWrapper(localName = "getTerminalsByIdsResponse", targetNamespace = "http://radvision.com/icm/service/resourceservice", className = "com.radvision.icm.service.GetTerminalsByIdsResponse")
    public List<TerminalResource> getTerminalsByIds(
        @WebParam(name = "terminalIds", targetNamespace = "")
        List<String> terminalIds);

    /**
     * 
     * @param classificationName
     * @param dialingInfo
     * @param name
     * @return
     *     returns java.util.List<com.radvision.icm.service.TerminalResource>
     * @throws NoClassificationFoundException_Exception
     * @throws InvalidArgumentException_Exception
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "searchTerminal", targetNamespace = "http://radvision.com/icm/service/resourceservice", className = "com.radvision.icm.service.SearchTerminal")
    @ResponseWrapper(localName = "searchTerminalResponse", targetNamespace = "http://radvision.com/icm/service/resourceservice", className = "com.radvision.icm.service.SearchTerminalResponse")
    public List<TerminalResource> searchTerminal(
        @WebParam(name = "classificationName", targetNamespace = "")
        String classificationName,
        @WebParam(name = "name", targetNamespace = "")
        String name,
        @WebParam(name = "dialingInfo", targetNamespace = "")
        String dialingInfo)
        throws InvalidArgumentException_Exception, NoClassificationFoundException_Exception
    ;

}
