
package com.radvision.icm.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.1-02/02/2007 03:56 AM(vivekp)-FCS
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ControlServicePortType", targetNamespace = "http://radvision.com/icm/service/controlservice")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ControlServicePortType {


    /**
     * 
     * @param extendTime
     * @param conferenceId
     * @return
     *     returns com.radvision.icm.service.ControlResult
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "extendLiveConference", targetNamespace = "http://radvision.com/icm/service/controlservice", className = "com.radvision.icm.service.ExtendLiveConference")
    @ResponseWrapper(localName = "extendLiveConferenceResponse", targetNamespace = "http://radvision.com/icm/service/controlservice", className = "com.radvision.icm.service.ExtendLiveConferenceResponse")
    public ControlResult extendLiveConference(
        @WebParam(name = "conferenceId", targetNamespace = "")
        String conferenceId,
        @WebParam(name = "extendTime", targetNamespace = "")
        long extendTime);

    /**
     * 
     * @param conferenceId
     * @return
     *     returns com.radvision.icm.service.ControlResult
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "terminateLiveConference", targetNamespace = "http://radvision.com/icm/service/controlservice", className = "com.radvision.icm.service.TerminateLiveConference")
    @ResponseWrapper(localName = "terminateLiveConferenceResponse", targetNamespace = "http://radvision.com/icm/service/controlservice", className = "com.radvision.icm.service.TerminateLiveConferenceResponse")
    public ControlResult terminateLiveConference(
        @WebParam(name = "conferenceId", targetNamespace = "")
        String conferenceId);

    /**
     * 
     * @param terminal
     * @param conferenceId
     * @return
     *     returns com.radvision.icm.service.ControlResult
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "inviteNewTerminal", targetNamespace = "http://radvision.com/icm/service/controlservice", className = "com.radvision.icm.service.InviteNewTerminal")
    @ResponseWrapper(localName = "inviteNewTerminalResponse", targetNamespace = "http://radvision.com/icm/service/controlservice", className = "com.radvision.icm.service.InviteNewTerminalResponse")
    public ControlResult inviteNewTerminal(
        @WebParam(name = "conferenceId", targetNamespace = "")
        String conferenceId,
        @WebParam(name = "terminal", targetNamespace = "")
        Terminal terminal);

    /**
     * 
     * @param terminal
     * @param conferenceId
     * @return
     *     returns com.radvision.icm.service.ControlResultEx
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "inviteNewTerminalEx", targetNamespace = "http://radvision.com/icm/service/controlservice", className = "com.radvision.icm.service.InviteNewTerminalEx")
    @ResponseWrapper(localName = "inviteNewTerminalExResponse", targetNamespace = "http://radvision.com/icm/service/controlservice", className = "com.radvision.icm.service.InviteNewTerminalExResponse")
    public ControlResultEx inviteNewTerminalEx(
        @WebParam(name = "conferenceId", targetNamespace = "")
        String conferenceId,
        @WebParam(name = "terminal", targetNamespace = "")
        Terminal terminal);

    /**
     * 
     * @param terminalId
     * @param conferenceId
     * @return
     *     returns com.radvision.icm.service.ControlResult
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "dropAttendedTerminal", targetNamespace = "http://radvision.com/icm/service/controlservice", className = "com.radvision.icm.service.DropAttendedTerminal")
    @ResponseWrapper(localName = "dropAttendedTerminalResponse", targetNamespace = "http://radvision.com/icm/service/controlservice", className = "com.radvision.icm.service.DropAttendedTerminalResponse")
    public ControlResult dropAttendedTerminal(
        @WebParam(name = "conferenceId", targetNamespace = "")
        String conferenceId,
        @WebParam(name = "terminalId", targetNamespace = "")
        String terminalId);

}
