
package com.radvision.icm.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.1-02/02/2007 03:56 AM(vivekp)-FCS
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ScheduleService", targetNamespace = "http://radvision.com/icm/service/scheduleservice", wsdlLocation = "file:/D:/Radvision/Product/icmservice/training/wsimport/wsdl/ScheduleService.wsdl")
public class ScheduleService
    extends Service
{

    private final static URL SCHEDULESERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("file:/D:/Radvision/Product/icmservice/training/wsimport/wsdl/ScheduleService.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        SCHEDULESERVICE_WSDL_LOCATION = url;
    }

    public ScheduleService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ScheduleService() {
        super(SCHEDULESERVICE_WSDL_LOCATION, new QName("http://radvision.com/icm/service/scheduleservice", "ScheduleService"));
    }

    /**
     * 
     * @return
     *     returns ScheduleServicePortType
     */
    @WebEndpoint(name = "ScheduleServicePort")
    public ScheduleServicePortType getScheduleServicePort() {
        return (ScheduleServicePortType)super.getPort(new QName("http://radvision.com/icm/service/scheduleservice", "ScheduleServicePort"), ScheduleServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ScheduleServicePortType
     */
    @WebEndpoint(name = "ScheduleServicePort")
    public ScheduleServicePortType getScheduleServicePort(WebServiceFeature... features) {
        return (ScheduleServicePortType)super.getPort(new QName("http://radvision.com/icm/service/scheduleservice", "ScheduleServicePort"), ScheduleServicePortType.class, features);
    }

}
